server:
  port: 9060

spring:
  application:
    name: auth2.0-center
  zipkin:
      base-url: http://10.10.8.2:9050
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://116.62.23.39:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root-123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 116.62.23.39
    port: 6379
    password: 123456
    database: 0
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://localhost:9010/eureka/
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
