server:
  port: 9023
spring:
  application:
    name: resource
  zipkin:
      base-url: http://10.10.8.2:9050
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://localhost:9010/eureka/
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
security:
  oauth2:
    resource:
      id: resource
      user-info-uri: http://localhost:9030/uaa/user
      prefer-token-info: false