server:
  port: 9050
spring:
  application:
    name: micro-service-monitor
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5 ##为了能够快速删除
    lease-expiration-duration-in-seconds: 10 ##为了能够快速删除
  client:
      service-url:
        defaultZone: http://register1:9010/eureka/,http://register2:9011/eureka/

###actuator监控点 start####
endpoints:
  health:
    sensitive: false
    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
management:
  security:
    enabled: false
###actuator监控点 end####
turbine:
  app-config-list: micro-a-service
  cluster-name-expression: "'default'"