server:
  port: 9020
spring:
  application:
    name: order-service
  zipkin:
      base-url: http://10.10.8.2:9050
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://register1:9010/eureka/,http://register2:9011/eureka/

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false


