spring:
  application:
    name: upload-service
  http:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2500MB
server:
  port: 9040
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://register1:9010/eureka/,http://register2:9011/eureka/

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
